services:
  app:
    restart: unless-stopped
    domainname: cicdfy.xyz # if you want to use your own domain
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - target: 3000
        mode: ingress
        published: 3000
    deploy:
      resources:
        reservations:
          cpus: '0.50'
          memory: 512M